@token1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGVtYWlsLmNvbSIsInN1YnNjcmlwdGlvbiI6InN0YXJ0ZXIiLCJ2ZXJpZnkiOnRydWUsImlhdCI6MTY4MDYzOTEwNn0.bIFaWBb8eCrteTyfR99OODrHBbLvcrVCeIB8OA_whkM
### REGISTER
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "email": "user1@email.com",
  "password": "nhd783jdol"
}
###
### LOGIN
GET http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "user1@email.com",
  "password": "nhd783jdol"
}

###

### GET simple
GET http://localhost:3000/api/contacts
Accept: application/json
Authorization: Bearer {{token1}}
###
GET http://localhost:3000/api/contacts/64005ebe93f0975ba9b7bdd7
Accept: application/json
Authorization: Bearer {{token1}}
###

### BY ID no owner
GET http://localhost:3000/api/contacts/63f1e79d4dc50cca4f43735b
Accept: application/json
Authorization: Bearer {{token1}}
###
### BY ID with owner
GET http://localhost:3000/api/contacts/642c87122969c63fa569e028
Accept: application/json
Authorization: Bearer {{token1}}
###

### CREATE CONTACT
POST http://localhost:3000/api/contacts
Content-Type: application/json
Authorization: Bearer {{token1}}

{
  "name": "joeNOWWW1",
  "email": "eeemmmaaaiiilll@com.com",
  "phone": "+380677777777"
}
###  CREATE CONTACT
POST http://localhost:3000/api/contacts
Content-Type: application/json
Authorization: Bearer {{token1}}

{
  "name": "joetNOWWW33",
  "email": "examp@email.com",
  "phone": "+111111162222"
}
###

DELETE http://localhost:3000/api/contacts/64070f608e9fd3651163de20
Accept: application/json
Authorization: Bearer {{token1}}

###
GET http://localhost:3000/api/contacts/64005ebe93f0975ba9b7bdd7
Authorization: Bearer {{token1}}
Accept: application/json
###
// todo: get by wrong id????

### UPDATE CONTACT
PATCH http://localhost:3000/api/contacts/642c87122969c63fa569e028
Content-Type: application/json
Authorization: Bearer {{token1}}

{
  "phone": "+380600001118"
}
###
GET http://localhost:3000/api/contacts/6408873f115c40d0247c37a6
Accept: application/json
Authorization: Bearer {{token1}}

###
PATCH http://localhost:3000/api/contacts/6401c6c4d15d964a6208a1f2/favorite
Content-Type: application/json
Authorization: Bearer {{token1}}

{
  "favorite": "false"
}



### GET All auth
GET http://localhost:3000/api/contacts
Accept: application/json
Authorization: Bearer {{token1}}
###

### GET All auth PAGINATION
GET http://localhost:3000/api/contacts?page=3&limit=5
Accept: application/json
Authorization: Bearer {{token1}}
###

### GET All auth PAGINATION & FAVORITE
GET http://localhost:3000/api/contacts?page=1&limit=5&favorite=true
Accept: application/json
Authorization: Bearer {{token1}}
###

POST http://localhost:3000/api/users/logout
Content-Type: application/json
Authorization: Bearer {{token1}}
###

### CURRENT
GET  http://localhost:3000/api/users/current
Accept: application/json
Authorization: Bearer {{token1}}
###